[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites_on_the_blockchain = "8Lw8tQWgYc64CCRxA9w4K36iTkhUYKpuHe56hU4wRTHi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
